### ISSUE TITLE
Feature request: timestamps

### ISSUE THREAD

**Issue by Loskir** [kOFReadie/BSDataPuller#14]
Please add timestamp field to update object
It will be useful to get the exact time when that update happened.

I am building a custom client for MapData and saving updates to a database. I'm using the timestamp of websocket message received because it is the most accurate one I could get.

But I noticed that there are some delays between game events and tracked timestamps. I think they are caused by network delays between sending the message and receiving it but I'm not sure.

Anyway, adding timestamp to update would be useful

**Comment by kOFReadie** [comment]
could do. what are the timestamps relative to? if they are relative to the map progress then you could plot the timestamp inbetween the song progress as that is read directly from the game (though now that i think of it that timer can be delayed sometimes)

**Comment by Loskir** [comment]
I mean absolute timestamps, milliseconds from jan 1st 1970.

but i've checked that again ant it turned out that network delays are hardly noticaeble. so it's not that necessary to add timestamps but anyway.

I'm trying to make a script that saves every event to the database as you play. then you feed your raw video recording to another script and it cuts each play to a different file based on saved data. And while start/end events don't have to be precise, i can't make auto-pause-cutter © work properly as it is delayed significantly.

I think the reason is that I can't align recording start time with real-world timestamp to calculate offsets precisely. I'm using file creation date but it's only precise to a whole second.

**Comment by kOFReadie** [comment]
oh yeah sure i can add epoch timestamps
